# **8 PUZZLE PROBLEM**

In [1]:
import numpy as np

def move_gen(state):
    neighbors = []
    zero_pos = np.argwhere(state == 0)
    if zero_pos.size == 0:
        return neighbors
    zero_pos = zero_pos[0]
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    for move in moves:
        new_pos = zero_pos + move
        if 0 <= new_pos[0] < 3 and 0 <= new_pos[1] < 3:
            new_state = state.copy()
            new_state[zero_pos[0], zero_pos[1]], new_state[new_pos[0], new_pos[1]] = new_state[new_pos[0], new_pos[1]], new_state[zero_pos[0], zero_pos[1]]
            neighbors.append(new_state)
    return neighbors

def is_goal(state):
    return np.array_equal(state, np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]]))

def occursIn(state, path):
    return any(np.array_equal(state, p) for p in path)

def removeSeen(neighbors, path):
    return [neighbor for neighbor in neighbors if not occursIn(neighbor, path)]

def reconstructPath(final_state, parents):
    path = [final_state]
    while final_state in parents:
        final_state = parents[final_state]
        path.insert(0, final_state)
    return path

def makePairs(state, neighbors):
    return [(state, neighbor) for neighbor in neighbors]

def dfs(state, depth, path, parents):
    if depth == 0:
        return None
    if is_goal(state):
        return path
    neighbors = move_gen(state)
    neighbors = removeSeen(neighbors, path)
    pairs = makePairs(state, neighbors)
    for parent, neighbor in pairs:
        parents[neighbor.tobytes()] = parent
        result = dfs(neighbor, depth - 1, path + [neighbor], parents)
        if result:
            return result
    return None

def dfid(start_state):
    for depth in range(1, 100):
        parents = {}
        path = dfs(start_state, depth, [start_state], parents)
        if path:
            return path
    return None

start_state = np.array([[1, 2, 3], [4, 5, 6], [0, 7, 8]])
path = dfid(start_state)

if path:
    for i, step in enumerate(path):
        print(f"Step {i}:\n{step}\n")
else:
    print("No solution found.")


Step 0:
[[1 2 3]
 [4 5 6]
 [0 7 8]]

Step 1:
[[1 2 3]
 [4 5 6]
 [7 0 8]]

Step 2:
[[1 2 3]
 [4 5 6]
 [7 8 0]]



Optimality: DFID can be optimal for the 8-Puzzle problem if the cost of each move is equal. DFID explores all possible paths up to a certain depth before increasing the depth limit, ensuring it finds the shortest solution first.

Completeness: DFID is complete for the 8-Puzzle problem, as it will eventually explore all possible configurations to find a solution if one exists. The iterative deepening aspect ensures that no potential solutions are overlooked.

# **WATER JUG PROBLEM**

In [2]:
def move_gen(state):
    jug1, jug2 = state
    capacity1, capacity2 = 3, 7
    possible_moves = [
        (capacity1, jug2),
        (jug1, capacity2),
        (0, jug2),
        (jug1, 0),
        (min(jug1 + jug2, capacity1), max(0, jug1 + jug2 - capacity1)),
        (max(0, jug1 + jug2 - capacity2), min(jug1 + jug2, capacity2))
    ]
    return possible_moves

def is_goal(state):
    return state == (2, 0)

def occursIn(state, path):
    return any(state == p for p in path)

def removeSeen(neighbors, path):
    return [neighbor for neighbor in neighbors if not occursIn(neighbor, path)]

def reconstructPath(final_state, parents):
    path = [final_state]
    while final_state in parents:
        final_state = parents[final_state]
        path.insert(0, final_state)
    return path

def makePairs(state, neighbors):
    return [(state, neighbor) for neighbor in neighbors]

def dfs(state, depth, path, parents):
    if depth == 0:
        return None
    if is_goal(state):
        return path
    neighbors = move_gen(state)
    neighbors = removeSeen(neighbors, path)
    pairs = makePairs(state, neighbors)
    for parent, neighbor in pairs:
        parents[neighbor] = parent
        result = dfs(neighbor, depth - 1, path + [neighbor], parents)
        if result:
            return result
    return None

def dfid(start_state):
    for depth in range(1, 100):
        parents = {}
        path = dfs(start_state, depth, [start_state], parents)
        if path:
            return path
    return None

start_state = (0, 0)
path = dfid(start_state)

if path:
    for i, step in enumerate(path):
        print(f"Step {i}: {step}")
else:
    print("No solution found.")


Step 0: (0, 0)
Step 1: (3, 0)
Step 2: (0, 3)
Step 3: (3, 3)
Step 4: (0, 6)
Step 5: (3, 6)
Step 6: (2, 7)
Step 7: (2, 0)


Optimality: DFID is also optimal in the Water Jug problem, provided all actions (filling, emptying, pouring) have the same cost. Since it explores solutions incrementally by depth, the first solution found will be the shortest one.

Completeness: DFID is complete for the Water Jug problem, as it explores all possible states (combinations of jug fill levels) in a systematic manner, ensuring a solution will be found if one exists.

# **GRAPH PROBLEM**

In [3]:
def move_gen(state):
    graph = {
        'A': ['B', 'C', 'D'],
        'B': ['A', 'E', 'F'],
        'C': ['A', 'G', 'H'],
        'D': ['A', 'I'],
        'E': ['B', 'J'],
        'F': ['B', 'K'],
        'G': ['C', 'L'],
        'H': ['C', 'M'],
        'I': ['D', 'N'],
        'J': ['E', 'O'],
        'K': ['F', 'P'],
        'L': ['G'],
        'M': ['H'],
        'N': ['I'],
        'O': ['J'],
        'P': ['K']
    }
    return graph[state]

def is_goal(state):
    return state == 'O'

def occursIn(state, path):
    return state in path

def removeSeen(neighbors, path):
    return [neighbor for neighbor in neighbors if not occursIn(neighbor, path)]

def reconstructPath(final_state, parents):
    path = [final_state]
    while final_state in parents:
        final_state = parents[final_state]
        path.insert(0, final_state)
    return path

def makePairs(state, neighbors):
    return [(state, neighbor) for neighbor in neighbors]

def dfs(state, depth, path, parents):
    if depth == 0:
        return None
    if is_goal(state):
        return path
    neighbors = move_gen(state)
    neighbors = removeSeen(neighbors, path)
    pairs = makePairs(state, neighbors)
    for parent, neighbor in pairs:
        parents[neighbor] = parent
        result = dfs(neighbor, depth - 1, path + [neighbor], parents)
        if result:
            return result
    return None

def dfid(start_state):
    for depth in range(1, 100):
        parents = {}
        path = dfs(start_state, depth, [start_state], parents)
        if path:
            return path
    return None

start_state = 'A'
path = dfid(start_state)

if path:
    for i, step in enumerate(path):
        print(f"Step {i}: {step}")
else:
    print("No solution found.")


Step 0: A
Step 1: B
Step 2: E
Step 3: J
Step 4: O


Optimality: DFID can be optimal for the Graph problem if all edges have the same weight. It finds the shortest path to the goal node first because it increases the depth limit iteratively, ensuring that shorter paths are considered before longer ones.

Completeness: DFID is complete for the Graph problem. It explores all possible nodes in a depth-limited manner, ensuring that the solution will be found if the goal node is reachable from the start node.

# Conclusion
Depth-First Iterative Deepening (DFID) is a powerful algorithm that combines the advantages of depth-first search (DFS) and breadth-first search (BFS). It is particularly useful when the depth of the solution is unknown, and it is both memory-efficient and optimal in scenarios where all actions have the same cost.

DFID uses memory efficiently by maintaining only the current path in memory, unlike BFS, which requires storing all nodes at the current level.

In summary, DFID is well-suited for problems like the 8-Puzzle, Water Jug, and Graph traversal, especially when memory constraints are a concern and an optimal solution is desired.