# **FIONA HARIA | 60009220048 | D1-2 | D040**

# **Distance Matrix**

In [56]:
def distance_matrixx(num_cities):
    distance_matrix = np.random.randint(1, 100, size=(num_cities, num_cities))
    distance_matrix = (distance_matrix + distance_matrix.T) / 2
    np.fill_diagonal(distance_matrix, 0)

    # Create city labels (optional)
    city_labels = [chr(ord('A') + i) for i in range(num_cities)]
    df = pd.DataFrame(distance_matrix, index=city_labels, columns=city_labels)
    print(f"Distance Matrix with City Labels ({num_cities} cities):")
    print(df)

    return distance_matrix

distance_matrixx(20)

Distance Matrix with City Labels (20 cities):
      A     B     C     D     E     F     G     H     I     J     K     L     M     N     O     P  \
A   0.0  19.5  84.5  44.5  24.0  66.0  51.0  78.0  68.5  36.0  41.0  46.5  77.5  54.5  57.0  34.5   
B  19.5   0.0  50.0  63.5  32.5  41.5  37.0  49.5  29.0  65.5  70.0  71.0  43.5  34.5  83.5  63.5   
C  84.5  50.0   0.0  65.5  31.5  48.0  73.0  60.5  35.0   9.0  65.0  59.0  55.0  90.5  47.5  55.0   
D  44.5  63.5  65.5   0.0  88.0  37.5  40.0  20.5  44.0  52.0  63.0  10.5  78.5   7.5  64.0  31.5   
E  24.0  32.5  31.5  88.0   0.0  30.5  38.5  71.0  55.0  19.0  69.0  67.5  49.5  46.5  75.0  69.5   
F  66.0  41.5  48.0  37.5  30.5   0.0  68.0  54.5  28.5  41.5  61.0  44.0  40.5  47.0  14.0  43.0   
G  51.0  37.0  73.0  40.0  38.5  68.0   0.0  79.0  51.5  53.0  17.5  19.0  61.0  49.0  47.5  51.5   
H  78.0  49.5  60.5  20.5  71.0  54.5  79.0   0.0  57.5  53.0  26.0  55.5  32.5  40.0  61.5  39.0   
I  68.5  29.0  35.0  44.0  55.0  28.5  51.5  

array([[ 0. , 19.5, 84.5, 44.5, 24. , 66. , 51. , 78. , 68.5, 36. , 41. ,
        46.5, 77.5, 54.5, 57. , 34.5, 71.5, 61. , 63.5, 56.5],
       [19.5,  0. , 50. , 63.5, 32.5, 41.5, 37. , 49.5, 29. , 65.5, 70. ,
        71. , 43.5, 34.5, 83.5, 63.5, 95. , 49. , 63.5, 74. ],
       [84.5, 50. ,  0. , 65.5, 31.5, 48. , 73. , 60.5, 35. ,  9. , 65. ,
        59. , 55. , 90.5, 47.5, 55. , 70.5, 48. , 25. , 65. ],
       [44.5, 63.5, 65.5,  0. , 88. , 37.5, 40. , 20.5, 44. , 52. , 63. ,
        10.5, 78.5,  7.5, 64. , 31.5, 76. , 77. , 68. , 70. ],
       [24. , 32.5, 31.5, 88. ,  0. , 30.5, 38.5, 71. , 55. , 19. , 69. ,
        67.5, 49.5, 46.5, 75. , 69.5, 64. , 72.5, 23. , 34.5],
       [66. , 41.5, 48. , 37.5, 30.5,  0. , 68. , 54.5, 28.5, 41.5, 61. ,
        44. , 40.5, 47. , 14. , 43. , 37.5, 37. , 67. , 95. ],
       [51. , 37. , 73. , 40. , 38.5, 68. ,  0. , 79. , 51.5, 53. , 17.5,
        19. , 61. , 49. , 47.5, 51.5, 50.5, 81.5, 80.5, 60.5],
       [78. , 49.5, 60.5, 20.5, 71. , 54.

## generating population matrix

In [57]:
import numpy as np

def generate_population(num_cities, population_size):

    population = []
    for _ in range(population_size):
        tour = np.random.permutation(num_cities)
        population.append(tour)
    return np.array(population)


## testing the above

In [58]:
population_size = 6
num_cities = 20
population = generate_population(num_cities, population_size)
print("Generated Population Matrix:")
print(population)

Generated Population Matrix:
[[ 8 13 14 10  1  3  9  6  2 12 15 19 18 16  7 17  0 11  4  5]
 [15  9 17 11  3  2  8  4 14  0 10 16 19  1  5 12 18  6  7 13]
 [ 1  6 11  8 19  7  5 10  4  3 16  0 13 17 15 14 18 12  2  9]
 [19 18 14  0 11  1  7  8  4 12  2  9 10  6  3 15 16 17 13  5]
 [13 16  5  0 11  4 15 14 17  7  6  2  3  8 19 12  9  1 10 18]
 [12  7  0 14  4  2 15 13  6  1 19 10  8  5 18  9 16  3 17 11]]


# FITNESS FUNCTION

## calculating the tour cost

In [59]:
def tour_cost(tour, distance_matrix):

    cost = 0
    for i in range(len(tour) - 1):
        cost += distance_matrix[tour[i], tour[i+1]]
    cost += distance_matrix[tour[-1], tour[0]]
    return cost


def calculate_population_cost(population, distance_matrix):
    costs = np.array([tour_cost(tour, distance_matrix) for tour in population])
    return costs


## testing the above

In [60]:
distance_matrix = np.random.rand(num_cities, num_cities)
distance_matrix = (distance_matrix + distance_matrix.T) / 2
costs = calculate_population_cost(population, distance_matrix)
print("Tour Costs:")
print(costs)

Tour Costs:
[ 9.45560929  9.42188655  8.74835355  9.01643301  8.77602218 10.45166441]


## Roulette Wheel **(Selection)**

In [61]:
def roulette_wheel_selection(costs, population):

    total_cost = np.sum(costs)
    selection_probs = 1 - (costs / total_cost)
    selection_probs /= np.sum(selection_probs)

    selected_indices = np.random.choice(range(len(population)), size=len(population), p=selection_probs)
    selected_population = population[selected_indices]
    return selected_population



## Test the above

In [62]:
selected_population = roulette_wheel_selection(costs, population)
print("Selected Population after Roulette Wheel:")
print(selected_population)


Selected Population after Roulette Wheel:
[[19 18 14  0 11  1  7  8  4 12  2  9 10  6  3 15 16 17 13  5]
 [ 1  6 11  8 19  7  5 10  4  3 16  0 13 17 15 14 18 12  2  9]
 [13 16  5  0 11  4 15 14 17  7  6  2  3  8 19 12  9  1 10 18]
 [13 16  5  0 11  4 15 14 17  7  6  2  3  8 19 12  9  1 10 18]
 [19 18 14  0 11  1  7  8  4 12  2  9 10  6  3 15 16 17 13  5]
 [ 1  6 11  8 19  7  5 10  4  3 16  0 13 17 15 14 18 12  2  9]]


In [63]:
def find_cycle(start, parent1, parent2):
    cycle = []
    current = start
    while current not in cycle:
        cycle.append(current)
        current = np.where(parent1 == parent2[current])[0][0]
    return cycle



## CYCLIC CROSSOVER

In [64]:
import numpy as np

def generate_random_population(num_individuals, num_genes):
    return np.array([np.random.permutation(num_genes) for _ in range(num_individuals)])

def find_cycle(start, parent1, parent2):
    cycle = []
    current = start
    while current not in cycle:
        cycle.append(current)
        current = np.where(parent1 == parent2[current])[0][0]
    return cycle

def cyclic_crossover(parent1, parent2):
    child1, child2 = np.copy(parent1), np.copy(parent2)
    mask1, mask2 = np.full_like(parent1, False, dtype=bool), np.full_like(parent2, False, dtype=bool)

    for i in range(len(parent1)):
        if not mask1[i]:
            cycle = find_cycle(i, parent1, parent2)
            for idx in cycle:
                child1[idx], child2[idx] = parent2[idx], parent1[idx]
                mask1[idx], mask2[idx] = True, True

    return child1, child2

def crossover_population(population):
    new_population = []
    for i in range(0, len(population), 2):
        parent1, parent2 = population[i], population[i+1]
        child1, child2 = cyclic_crossover(parent1, parent2)
        new_population.extend([child1, child2])
    return np.array(new_population)




## TESTING THE ABOVE

In [65]:
#Generate random population
np.random.seed(42)
num_individuals = 6
num_genes = 20
population = generate_random_population(num_individuals, num_genes)

# Print initial population
print("Initial Population:")
print(population)

# Perform crossover
crossed_population = crossover_population(population)

# Print population after first iteration of crossover
print("\nPopulation after Cyclic Crossover:")
print(crossed_population)

Initial Population:
[[ 0 17 15  1  8  5 11  3 18 16 13  2  9 19  4 12  7 10 14  6]
 [19 16 15  5  4 12 14  7  3  6  2  9 13 10 18  8 17 11  0  1]
 [10  7  0  2  5 18 16 12  4 14 15  9  1 13 11 19  3 17  6  8]
 [ 0 18  6  8 17 11  4  9 12 10  5 19 15  7  1  3 16 13  2 14]
 [ 5  2 10 19  0 12  9 16  1  4 17  8 11  6 18  7 14 15 13  3]
 [ 3  1  4  5 15 16  9 10 13  2 18 19 11 17  7  8  6  0 12 14]]

Population after Cyclic Crossover:
[[19 16 15  5  4 12 14  7  3  6  2  9 13 10 18  8 17 11  0  1]
 [ 0 17 15  1  8  5 11  3 18 16 13  2  9 19  4 12  7 10 14  6]
 [ 0 18  6  8 17 11  4  9 12 10  5 19 15  7  1  3 16 13  2 14]
 [10  7  0  2  5 18 16 12  4 14 15  9  1 13 11 19  3 17  6  8]
 [ 3  1  4  5 15 16  9 10 13  2 18 19 11 17  7  8  6  0 12 14]
 [ 5  2 10 19  0 12  9 16  1  4 17  8 11  6 18  7 14 15 13  3]]


## MUTATION

In [66]:
def mutate(tour, mutation_rate=0.1):
    for _ in range(int(len(tour) * mutation_rate)):
        i, j = np.random.randint(0, len(tour), 2)
        tour[i], tour[j] = tour[j], tour[i]
    return tour

def mutate_population(population, mutation_rate=0.1):
    for i in range(len(population)):
        population[i] = mutate(population[i], mutation_rate)
    return population




## testing the above

In [67]:
mutated_population = mutate_population(crossed_population)
print("Population after Mutation:")
print(mutated_population)

Population after Mutation:
[[19 16 15  5  4 12 14  7  3  6  2  9 13 10 18  8 17 11  0  1]
 [17  0 15  1  8  5 11  2 18 16 13  3  9 19  4 12  7 10 14  6]
 [ 0 18 19  8  3 11  4  9 12 10  5  6 15  7  1 17 16 13  2 14]
 [12  7 10  2  5 18 16  0  4 14 15  9  1 13 11 19  3 17  6  8]
 [ 3  1 17  5  7 16  9 10 13  2 18 19 11  4 15  8  6  0 12 14]
 [ 0  2 10 19  5 12  6 16  1  4 17  8 11  9 18  7 14 15 13  3]]


## CODE FOR GENETIC ALGORITHM

In [68]:
def genetic_algorithm(num_cities, population_size, num_iterations, distance_matrix, mutation_rate=0.1):
    population = generate_population(num_cities, population_size)
    for iteration in range(1, num_iterations + 1):
        costs = calculate_population_cost(population, distance_matrix)
        selected_population = roulette_wheel_selection(costs, population)
        crossed_population = crossover_population(selected_population)
        population = mutate_population(crossed_population, mutation_rate)

        # Convergence check
        min_cost = np.min(costs)
        print(f"Iteration {iteration}: Minimum Tour Cost = {min_cost}")

        if iteration > 1 and np.isclose(min_cost, prev_min_cost, atol=1e-4):
            print(f"Algorithm converged at iteration {iteration}")
            break

        prev_min_cost = min_cost

    return population, min_cost

# Test the full Genetic Algorithm
num_iterations = 100
final_population, final_cost = genetic_algorithm(num_cities, population_size, num_iterations, distance_matrix)
print("Final Population and Cost after Convergence:")
print(final_population)
print(final_cost)


Iteration 1: Minimum Tour Cost = 8.693623958539805
Iteration 2: Minimum Tour Cost = 8.901943956180864
Iteration 3: Minimum Tour Cost = 8.935760470889988
Iteration 4: Minimum Tour Cost = 9.923152878286064
Iteration 5: Minimum Tour Cost = 8.489758289016887
Iteration 6: Minimum Tour Cost = 8.842199463370497
Iteration 7: Minimum Tour Cost = 8.161409882643454
Iteration 8: Minimum Tour Cost = 7.760593905815168
Iteration 9: Minimum Tour Cost = 9.314594202150777
Iteration 10: Minimum Tour Cost = 8.517082138417912
Iteration 11: Minimum Tour Cost = 8.11295499594707
Iteration 12: Minimum Tour Cost = 7.6357510916444165
Iteration 13: Minimum Tour Cost = 7.1730525249043895
Iteration 14: Minimum Tour Cost = 7.062168062123763
Iteration 15: Minimum Tour Cost = 8.185354526645174
Iteration 16: Minimum Tour Cost = 8.168487333730795
Iteration 17: Minimum Tour Cost = 9.01286449328215
Iteration 18: Minimum Tour Cost = 9.413339751784283
Iteration 19: Minimum Tour Cost = 8.818721370578416
Iteration 20: Minimum

In [71]:
def run_ga_for_city_sizes():
    city_sizes = [5, 10, 20, 40]  # List of city sizes
    population_size = 50
    num_iterations = 100
    mutation_rate = 0.1
    results = {}

    for num_cities in city_sizes:
        print(f"\nRunning Genetic Algorithm for {num_cities} cities:\n")

        # Generate distance matrix for the current number of cities
        distance_matrix = distance_matrixx(num_cities)

        # Run the genetic algorithm and store the results
        final_population, final_cost = genetic_algorithm(num_cities, population_size, num_iterations, distance_matrix, mutation_rate)
        results[num_cities] = final_cost
        print(f"Final minimum cost for {num_cities} cities: {final_cost}")

    # Summary of results
    print("\nSummary of results:")
    for num_cities, final_cost in results.items():
        print(f"{num_cities} cities: Final minimum cost = {final_cost}")

run_ga_for_city_sizes()


Running Genetic Algorithm for 5 cities:

Distance Matrix with City Labels (5 cities):
      A     B     C     D     E
A   0.0  67.0  85.5  55.0  63.5
B  67.0   0.0  86.5  17.5  37.0
C  85.5  86.5   0.0  54.0  48.0
D  55.0  17.5  54.0   0.0  57.0
E  63.5  37.0  48.0  57.0   0.0
Iteration 1: Minimum Tour Cost = 243.0
Iteration 2: Minimum Tour Cost = 243.0
Algorithm converged at iteration 2
Final minimum cost for 5 cities: 243.0

Running Genetic Algorithm for 10 cities:

Distance Matrix with City Labels (10 cities):
      A     B     C     D     E     F     G     H     I     J
A   0.0  29.5  44.5  59.0  76.5  22.5  42.0  59.0  43.0  45.0
B  29.5   0.0  44.5  59.0  41.5  36.0  48.5  18.5  67.0  66.5
C  44.5  44.5   0.0  26.5  50.0  68.5  33.5  29.0  48.0  29.5
D  59.0  59.0  26.5   0.0   4.0  47.5  67.0  64.5  85.5  67.5
E  76.5  41.5  50.0   4.0   0.0  57.0  45.0  77.5  69.5  52.0
F  22.5  36.0  68.5  47.5  57.0   0.0  51.5  45.0  29.5  56.5
G  42.0  48.5  33.5  67.0  45.0  51.5   0.0  5